@echo off
cd /d "%~dp0.."
REM ========================================================
REM requirements.txt auto-generation batch file
REM   Writes a pip freeze of .venv, excluding the packages that are
REM   only needed for the Windows exe build (PyInstaller and friends).
REM   Those are managed in requirements-build.txt instead.
REM   Keep the findstr filter below in sync with requirements-build.txt.
REM ========================================================

echo.
echo =======================================================
echo Creating requirements.txt for the current environment...
echo =======================================================
echo.

echo Activating virtual environment...
call .\.venv\Scripts\activate
echo Virtual environment activated.
echo.

echo Generating library list using 'pip freeze'...
REM NOTE: do not put parentheses in the echoed lines below -- a ')' inside a
REM parenthesized block closes the block early and breaks the redirection.
(
    echo # Runtime/test dependencies for the app. Auto-generated by scripts\create_requirements.bat
    echo # Windows exe build dependencies: see requirements-build.txt
    pip freeze | findstr /v /i /r /c:"^pyinstaller" /c:"^pefile" /c:"^pywin32-ctypes" /c:"^altgraph"
) > requirements.txt
echo.

echo =======================================================
echo 'requirements.txt' has been created successfully!
echo =======================================================
echo.
pause
